targetScope = 'resourceGroup'

@description('Short environment name used in resource names and tags.')
param environmentName string

@description('Primary Azure region for the platform.')
param location string

@description('Whether to provision Azure OpenAI.')
param enableAi bool

@description('Azure region for Azure OpenAI. Model availability and quota vary by region.')
param aiLocation string

@description('Capacity of the Global Standard Azure OpenAI model deployment.')
@minValue(1)
param aiModelCapacity int

@secure()
@description('Stable PostgreSQL administrator password generated by the azd preprovision hook.')
param databasePassword string

@secure()
@description('Stable NextAuth signing secret generated by the azd preprovision hook.')
param nextAuthSecret string

@description('Authentication providers enabled for the web application.')
@allowed([
  'demo'
  'entra'
  'hybrid'
])
param authenticationMode string

@description('Directory tenant ID of the Microsoft Entra External ID tenant.')
param externalIdTenantId string

@description('Subdomain of the Microsoft Entra External ID tenant.')
param externalIdTenantSubdomain string

@description('Application client ID registered in the Microsoft Entra External ID tenant.')
param externalIdClientId string

@secure()
@description('Application client secret registered in the Microsoft Entra External ID tenant.')
param externalIdClientSecret string

@description('Directory tenant ID of the council workforce tenant.')
param workforceTenantId string

@description('Application client ID registered in the council workforce tenant.')
param workforceClientId string

@secure()
@description('Application client secret registered in the council workforce tenant.')
param workforceClientSecret string

@secure()
@description('Stable synthetic demo account password generated by the azd preprovision hook.')
param demoPassword string

@description('Whether the migrations job also seeds synthetic demo data.')
param seedDemoData bool

@description('Public display name of the application.')
param applicationName string

@description('Public support email address.')
param supportEmail string

@description('Public support telephone number.')
param supportPhone string

@description('Whether demo mode is enabled.')
param demoMode bool

@description('Whether to display the sample-data banner.')
param showSampleBanner bool

@description('Additional tags applied to every resource.')
param tags object = {}

var environmentAlphaNumeric = replace(replace(toLower(environmentName), '-', ''), '_', '')
var environmentSuffix = take(environmentAlphaNumeric, 10)
var uniqueToken = take(uniqueString(subscription().id, resourceGroup().id, environmentName), 10)
var baseTags = union(tags, {
  'azd-env-name': environmentName
  environment: environmentName
  solution: 'digital-permit-platform'
  'managed-by': 'azd'
})
var postgresAdministratorLogin = 'dppadmin'
var postgresDatabaseName = 'digital_permits'
var openAiDeploymentName = 'gpt-4.1-mini'
var openAiApiVersion = '2024-10-21'

var virtualNetworkName = 'vnet-dpp-${environmentSuffix}'
var logAnalyticsName = 'log-dpp-${environmentSuffix}'
var applicationInsightsName = 'appi-dpp-${environmentSuffix}'
var containerEnvironmentName = 'cae-dpp-${environmentSuffix}'
var registryName = take('crdpp${environmentSuffix}${uniqueToken}', 50)
var storageAccountName = take('stdpp${environmentSuffix}${uniqueToken}', 24)
var keyVaultName = take('kv-dpp-${environmentSuffix}-${uniqueToken}', 24)
var postgresServerName = take('psql-dpp-${environmentSuffix}-${uniqueToken}', 63)
var redisName = take('redis-dpp-${environmentSuffix}-${uniqueToken}', 60)
var openAiName = take('oai-dpp-${environmentSuffix}-${uniqueToken}', 64)
var webIdentityName = 'id-dpp-${environmentSuffix}-web'
var workerIdentityName = 'id-dpp-${environmentSuffix}-worker'
var migrationsIdentityName = 'id-dpp-${environmentSuffix}-migrations'
var webAppName = take('dpp-${environmentSuffix}-web', 32)
var workerAppName = take('dpp-${environmentSuffix}-worker', 32)
var migrationsJobName = take('dpp-${environmentSuffix}-migrations', 32)

module network './network.bicep' = {
  name: 'network'
  params: {
    location: location
    virtualNetworkName: virtualNetworkName
    tags: baseTags
  }
}

module identities './identities.bicep' = {
  name: 'identities'
  params: {
    location: location
    webIdentityName: webIdentityName
    workerIdentityName: workerIdentityName
    migrationsIdentityName: migrationsIdentityName
    tags: baseTags
  }
}

module logAnalytics 'br/public:avm/res/operational-insights/workspace:0.16.1' = {
  name: 'log-analytics'
  params: {
    name: logAnalyticsName
    location: location
    skuName: 'PerGB2018'
    storageInsightsConfigs: []
    linkedServices: []
    linkedStorageAccounts: []
    savedSearches: []
    dataExports: []
    dataSources: []
    tables: []
    gallerySolutions: []
    onboardWorkspaceToSentinel: false
    dataRetention: 30
    dailyQuotaGb: '-1'
    defaultDataCollectionRuleResourceId: null
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
    managedIdentities: null
    features: null
    replication: null
    diagnosticSettings: []
    forceCmkForQuery: false
    lock: null
    roleAssignments: []
    tags: baseTags
    enableTelemetry: false
  }
}

module applicationInsights 'br/public:avm/res/insights/component:0.8.0' = {
  name: 'application-insights'
  params: {
    name: applicationInsightsName
    applicationType: 'web'
    workspaceResourceId: logAnalytics.outputs.resourceId
    disableIpMasking: false
    disableLocalAuth: false
    forceCustomerStorageForProfiler: false
    linkedStorageAccountResourceId: null
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
    retentionInDays: 90
    samplingPercentage: 100
    flowType: null
    requestSource: null
    kind: 'web'
    immediatePurgeDataOn30Days: false
    ingestionMode: null
    location: location
    lock: null
    roleAssignments: []
    tags: baseTags
    enableTelemetry: false
    diagnosticSettings: []
  }
}

module registry 'br/public:avm/res/container-registry/registry:0.12.1' = {
  name: 'container-registry'
  params: {
    name: registryName
    acrAdminUserEnabled: false
    location: location
    roleAssignments: []
    autoGeneratedDomainNameLabelScope: null
    roleAssignmentMode: 'LegacyRegistryPermissions'
    acrSku: 'Basic'
    publicNetworkAccess: 'Enabled'
    networkRuleSetIpRules: []
    privateEndpoints: []
    replications: []
    webhooks: []
    lock: null
    managedIdentities: null
    tags: baseTags
    enableTelemetry: false
    diagnosticSettings: []
    customerManagedKey: null
    cacheRules: []
    credentialSets: []
    scopeMaps: []
    tokens: []
    tasks: []
  }
}

module storage 'br/public:avm/res/storage/storage-account:0.33.0' = {
  name: 'storage'
  params: {
    name: storageAccountName
    location: location
    extendedLocationZone: null
    roleAssignments: []
    managedIdentities: null
    kind: 'StorageV2'
    skuName: 'Standard_LRS'
    accessTier: 'Hot'
    azureFilesIdentityBasedAuthentication: null
    defaultToOAuthAuthentication: true
    allowSharedKeyAccess: false
    privateEndpoints: []
    managementPolicyRules: []
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      ipRules: []
      virtualNetworkRules: []
      resourceAccessRules: []
    }
    allowCrossTenantReplication: false
    dnsEndpointType: 'Standard'
    blobServices: {
      containerDeleteRetentionPolicyEnabled: true
      containerDeleteRetentionPolicyDays: 7
      deleteRetentionPolicyEnabled: true
      deleteRetentionPolicyDays: 7
      isVersioningEnabled: true
      containers: [
        {
          name: 'documents'
          publicAccess: 'None'
        }
        {
          name: 'exports'
          publicAccess: 'None'
        }
      ]
    }
    enableHierarchicalNamespace: false
    localUsers: []
    diagnosticSettings: []
    lock: null
    tags: baseTags
    enableTelemetry: false
    allowedCopyScope: null
    publicNetworkAccess: 'Enabled'
    supportsHttpsTrafficOnly: true
    customerManagedKey: null
    keyType: null
    secretsExportConfiguration: null
    immutableStorageWithVersioning: null
    objectReplicationPolicies: []
  }
}

module postgres 'br/public:avm/res/db-for-postgre-sql/flexible-server:0.16.0' = {
  name: 'postgresql'
  params: {
    name: postgresServerName
    administratorLogin: postgresAdministratorLogin
    administratorLoginPassword: databasePassword
    administrators: []
    authConfig: {
      activeDirectoryAuth: 'Disabled'
      passwordAuth: 'Enabled'
    }
    location: location
    skuName: 'Standard_B1ms'
    tier: 'Burstable'
    availabilityZone: -1
    highAvailability: 'Disabled'
    backupRetentionDays: 14
    geoRedundantBackup: 'Disabled'
    storageSizeGB: 32
    autoGrow: 'Enabled'
    storageType: null
    storageTier: null
    storageIops: null
    storageThroughput: null
    version: '16'
    managedIdentities: null
    customerManagedKey: null
    delegatedSubnetResourceId: network.outputs.postgresSubnetResourceId
    privateDnsZoneArmResourceId: network.outputs.postgresPrivateDnsZoneResourceId
    firewallRules: []
    publicNetworkAccess: 'Disabled'
    databases: [
      {
        name: postgresDatabaseName
        charset: 'UTF8'
        collation: 'en_US.utf8'
      }
    ]
    configurations: [
      {
        name: 'require_secure_transport'
        value: 'on'
        source: 'user-override'
      }
    ]
    lock: null
    replica: null
    roleAssignments: []
    tags: baseTags
    enableTelemetry: false
    diagnosticSettings: []
    privateEndpoints: []
  }
}

module redis 'br/public:avm/res/cache/redis-enterprise:0.5.1' = {
  name: 'managed-redis'
  params: {
    location: location
    name: redisName
    publicNetworkAccess: 'Enabled'
    lock: null
    roleAssignments: []
    tags: baseTags
    managedIdentities: null
    customerManagedKey: null
    highAvailability: 'Enabled'
    minimumTlsVersion: '1.2'
    skuName: 'Balanced_B0'
    database: {
      name: 'default'
      accessKeysAuthentication: 'Enabled'
      clientProtocol: 'Encrypted'
      clusteringPolicy: 'NoCluster'
      evictionPolicy: 'VolatileLRU'
      port: 10000
    }
    privateEndpoints: []
    diagnosticSettings: []
    enableTelemetry: false
  }
}

module openAi 'br/public:avm/res/cognitive-services/account:0.17.0' = if (enableAi) {
  name: 'azure-openai'
  params: {
    name: openAiName
    kind: 'OpenAI'
    sku: 'S0'
    location: aiLocation
    diagnosticSettings: []
    publicNetworkAccess: 'Enabled'
    customSubDomainName: openAiName
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      ipRules: []
      virtualNetworkRules: []
    }
    networkInjections: null
    privateEndpoints: []
    lock: null
    roleAssignments: []
    tags: baseTags
    allowedFqdnList: []
    apiProperties: {}
    disableLocalAuth: true
    customerManagedKey: null
    migrationToken: null
    restrictOutboundNetworkAccess: false
    userOwnedStorage: []
    managedIdentities: null
    enableTelemetry: false
    deployments: [
      {
        name: openAiDeploymentName
        model: {
          format: 'OpenAI'
          name: 'gpt-4.1-mini'
          version: '2025-04-14'
        }
        sku: {
          name: 'GlobalStandard'
          capacity: aiModelCapacity
        }
        versionUpgradeOption: 'NoAutoUpgrade'
      }
    ]
    secretsExportConfiguration: null
    allowProjectManagement: false
    commitmentPlans: []
    enableDefenderForAI: false
  }
}

var databaseUrl = 'postgresql://${postgresAdministratorLogin}:${uriComponent(databasePassword)}@${postgres.outputs.?fqdn ?? ''}:5432/${postgresDatabaseName}?schema=public&sslmode=require'
var redisUrl = 'rediss://default:${uriComponent(redis.outputs.?primaryAccessKey ?? '')}@${redis.outputs.?hostName ?? ''}:${redis.outputs.?port ?? 10000}'
var entraEnabled = authenticationMode == 'entra' || authenticationMode == 'hybrid'

module keyVault 'br/public:avm/res/key-vault/vault:0.14.0' = {
  name: 'key-vault'
  params: {
    name: keyVaultName
    location: location
    accessPolicies: []
    secrets: concat([
      {
        name: 'database-url'
        value: databaseUrl
        contentType: 'Prisma PostgreSQL connection URL'
      }
      {
        name: 'redis-url'
        value: redisUrl
        contentType: 'BullMQ TLS Redis URL'
      }
      {
        name: 'nextauth-secret'
        value: nextAuthSecret
        contentType: 'NextAuth signing secret'
      }
      {
        name: 'demo-password'
        value: demoPassword
        contentType: 'Synthetic demo account password'
      }
      {
        name: 'applicationinsights-connection-string'
        value: applicationInsights.outputs.connectionString
        contentType: 'Application Insights connection string'
      }
    ], entraEnabled ? [
      {
        name: 'entra-external-id-client-secret'
        value: externalIdClientSecret
        contentType: 'Microsoft Entra External ID application client secret'
      }
      {
        name: 'entra-workforce-client-secret'
        value: workforceClientSecret
        contentType: 'Microsoft Entra workforce application client secret'
      }
    ] : [])
    keys: []
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enableRbacAuthorization: true
    enablePurgeProtection: true
    sku: 'standard'
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      ipRules: []
      virtualNetworkRules: []
    }
    publicNetworkAccess: 'Enabled'
    lock: null
    roleAssignments: []
    privateEndpoints: []
    tags: baseTags
    diagnosticSettings: []
    enableTelemetry: false
  }
}

module managedEnvironment 'br/public:avm/res/app/managed-environment:0.15.0' = {
  name: 'container-apps-environment'
  params: {
    name: containerEnvironmentName
    location: location
    tags: baseTags
    managedIdentities: null
    roleAssignments: []
    lock: null
    privateEndpoints: []
    diagnosticSettings: []
    enableTelemetry: false
    daprConfiguration: null
    ingressConfiguration: null
    kedaConfiguration: null
    peerAuthentication: null
    infrastructureSubnetResourceId: network.outputs.containerAppsSubnetResourceId
    internal: false
    publicNetworkAccess: 'Enabled'
    peerTrafficEncryption: false
    zoneRedundant: false
    certificateValue: null
    openTelemetryConfiguration: null
    workloadProfiles: []
    storages: []
    certificate: null
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsWorkspaceResourceId: logAnalytics.outputs.resourceId
    }
  }
}

module rbac './rbac.bicep' = {
  name: 'rbac'
  params: {
    registryResourceId: registry.outputs.resourceId
    storageResourceId: storage.outputs.resourceId
    keyVaultResourceId: keyVault.outputs.resourceId
    enableEntra: entraEnabled
    enableAi: enableAi
    openAiResourceId: openAi.?outputs.?resourceId ?? ''
    webPrincipalId: identities.outputs.webPrincipalId
    workerPrincipalId: identities.outputs.workerPrincipalId
    migrationsPrincipalId: identities.outputs.migrationsPrincipalId
  }
}

module applications './applications.bicep' = {
  name: 'applications'
  params: {
    location: location
    environmentResourceId: managedEnvironment.outputs.resourceId
    environmentDefaultDomain: managedEnvironment.outputs.defaultDomain
    webAppName: webAppName
    workerAppName: workerAppName
    migrationsJobName: migrationsJobName
    webIdentityResourceId: identities.outputs.webResourceId
    workerIdentityResourceId: identities.outputs.workerResourceId
    migrationsIdentityResourceId: identities.outputs.migrationsResourceId
    registryLoginServer: registry.outputs.loginServer
    keyVaultUri: keyVault.outputs.uri
    storageAccountName: storage.outputs.name
    openAiEndpoint: openAi.?outputs.?endpoint ?? ''
    openAiDeploymentName: openAiDeploymentName
    openAiApiVersion: openAiApiVersion
    authenticationMode: authenticationMode
    externalIdTenantId: externalIdTenantId
    externalIdTenantSubdomain: externalIdTenantSubdomain
    externalIdClientId: externalIdClientId
    workforceTenantId: workforceTenantId
    workforceClientId: workforceClientId
    applicationName: applicationName
    supportEmail: supportEmail
    supportPhone: supportPhone
    demoMode: demoMode ? 'true' : 'false'
    showSampleBanner: showSampleBanner ? 'true' : 'false'
    seedDemoData: seedDemoData ? 'true' : 'false'
    tags: baseTags
  }
  dependsOn: [
    rbac
  ]
}

output registryName string = registry.outputs.name
output registryLoginServer string = registry.outputs.loginServer
output webUri string = applications.outputs.webUri
output webAppName string = applications.outputs.webAppName
output workerAppName string = applications.outputs.workerAppName
output migrationsJobName string = applications.outputs.migrationsJobName
output storageAccountName string = storage.outputs.name
output keyVaultName string = keyVault.outputs.name
output openAiEndpoint string = openAi.?outputs.?endpoint ?? ''