"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Sparkles, Loader2, AlertTriangle, RefreshCw } from "lucide-react";
import { CompliancePanel } from "./licence-analyser";
import type { ComplianceAssessment } from "@/lib/ai/types";

type Status = "PENDING" | "PROCESSING" | "COMPLETE" | "FAILED";

interface Insight {
  status: Status;
  ragRating?: string | null;
  insight?: ComplianceAssessment | null;
  errorMessage?: string | null;
  tokensUsed?: number;
}

export function ApplicationInsight({ applicationId }: { applicationId: string }) {
  const [insight, setInsight] = useState<Insight | null>(null);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const stop = useCallback(() => {
    if (pollRef.current) clearInterval(pollRef.current);
    pollRef.current = null;
  }, []);

  const load = useCallback(async () => {
    try {
      const res = await fetch(
        `/api/ai/application-insight?applicationId=${applicationId}`
      );
      const data = await res.json();
      if (res.ok) {
        setInsight(data.insight);
        if (data.stale) {
          setError("A previous insight used a different policy. Generate a new insight for the active policy.");
        }
      }
    } finally {
      setLoading(false);
    }
  }, [applicationId]);

  useEffect(() => {
    load();
    return () => stop();
  }, [load, stop]);

  const poll = useCallback(() => {
    pollRef.current = setInterval(async () => {
      const res = await fetch(
        `/api/ai/application-insight?applicationId=${applicationId}`
      );
      const data = await res.json();
      if (res.ok && data.insight) {
        setInsight(data.insight);
        if (data.insight.status === "COMPLETE" || data.insight.status === "FAILED") {
          stop();
          setRunning(false);
          if (data.insight.status === "FAILED") {
            setError(data.insight.errorMessage || "Insight failed.");
          }
        }
      }
    }, 2500);
  }, [applicationId, stop]);

  async function generate() {
    setError(null);
    setRunning(true);
    try {
      const res = await fetch("/api/ai/application-insight", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ applicationId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Could not start insight.");
      setInsight({ status: "PROCESSING" });
      poll();
    } catch (e) {
      setRunning(false);
      setError((e as Error).message);
    }
  }

  const isProcessing = running || insight?.status === "PROCESSING";

  return (
    <section className="bg-white border border-govuk-mid-grey p-6">
      <div className="flex items-center justify-between gap-3 flex-wrap mb-2">
        <h2 className="flex items-center gap-2 !mb-0">
          <Sparkles className="h-5 w-5 text-govuk-blue" /> AI policy insight
        </h2>
        {insight?.status === "COMPLETE" && !isProcessing && (
          <button
            type="button"
            onClick={generate}
            className="text-sm text-govuk-blue underline flex items-center gap-1"
          >
            <RefreshCw className="h-4 w-4" /> Regenerate
          </button>
        )}
      </div>
      <p className="govuk-hint">
        An automatic check against the active council policy for this licence type.
      </p>

      {loading ? (
        <p className="text-govuk-dark-grey text-sm">Loading…</p>
      ) : isProcessing ? (
        <div className="flex items-center gap-2 text-govuk-dark-grey py-4">
          <Loader2 className="h-5 w-5 animate-spin text-govuk-blue" />
          Assessing this application against policy…
        </div>
      ) : insight?.status === "COMPLETE" && insight.insight ? (
        <div className="mt-2">
          <CompliancePanel compliance={insight.insight} />
          {typeof insight.tokensUsed === "number" && insight.tokensUsed > 0 && (
            <p className="text-xs text-govuk-dark-grey mt-2">
              Generated by Azure OpenAI · {insight.tokensUsed.toLocaleString()} tokens.
            </p>
          )}
        </div>
      ) : (
        <div className="py-2">
          {error && (
            <div className="mb-3 govuk-warning-text">
              <AlertTriangle className="h-5 w-5 text-govuk-red shrink-0" />
              <p className="text-sm">{error}</p>
            </div>
          )}
          <button type="button" onClick={generate} className="govuk-button">
            <Sparkles className="h-4 w-4 mr-1" /> Generate AI insight
          </button>
        </div>
      )}
    </section>
  );
}
